import streamlit as st
import pandas as pd
import uuid
from datetime import datetime
from supabase import create_client

st.set_page_config(page_title="BRISCO", layout="centered")

# -------supabase---------- 
url = st.secrets["SUPABASE_URL"] 
key = st.secrets["SUPABASE_KEY"] 
supabase = create_client(url, key)

# ---------------------------
# LOAD USERS (SAFE)
# ---------------------------
try:
    response = supabase.table("users").select("*").execute()
    users_data = response.data if response.data else []
    users_df = pd.DataFrame(users_data)
except Exception as e:
    st.error("❌ Could not load users")
    users_df = pd.DataFrame(columns=["user_id", "profession", "country"])

# ---------------------------
# UI: WELCOME PAGE
# ---------------------------
st.title("Welcome to BRISCO") 

st.markdown("""



BRISCO stands for **B**reast M**RI** **S**egmentation S**CO**ring. 
It is a plug-and-play web application designed for radiologists to evaluate the quality of breast MRI lesion segmentations, whether manual or generated by AI.


---

### Terms of Use 

**How to use?** Only NIFTII files upto 200 MB are elligible for input. The web. app. is hosted through streamlit free version hence it may occasionally sleep and function slow. 
All information related to a user can be deleted by the user themselves by clicking the button. 

**Data privacy:** Only the entries 'Profession', 'Country' are stored at the backend in Supabase to show the dashboard analytics and depict the use of the web. app. over time. 
NIFTI data input is not collected at the backend. The form entries are being stored in Supabase so that users can login again and also have access to their previous login entries. 

Tech stacks used: Supabase ( ), 

**Contacts:** This work has been developed by the researchers working at the Research Centre for Medical Image Analysis and AI, Department of Medicine, Danube Private University (DPU), Krems-3500, Austria. 
For queries or bugs related to the interface, email: Palak.Handa@dp-uni.ac.at. For queries related to the scoring form, email: Ramona.Woitek@dp-uni.ac.at

**Licence:** CC BY-NC. Commercial use is prohibited. Research collaborations and suggestions are welcome for further improvements. Credit must be given to the creaters. Hence, users must cite the following when using the code, data, web app, or any information generated through the web. app. 
{bibtex of the github}
{bibtex of the manuscript preprint}

""")

# ---------------------------
# NAVIGATION STATE
# ---------------------------
if "page" not in st.session_state:
    st.session_state.page = "home"

col1, col2 = st.columns(2)

with col1:
    if st.button("To Enter as an Existing User"):
        st.session_state.page = "login"

with col2:
    if st.button("To apply as a New User"):
        st.session_state.page = "register"

# ---------------------------
# LOGIN
# ---------------------------
if st.session_state.page == "login":
    st.subheader("Login")

    user_id_input = st.text_input("Enter User ID")

    if st.button("Login"):
        if users_df.empty:
            st.error("No users registered yet")
        elif user_id_input in users_df["user_id"].astype(str).values:
            st.session_state.user_id = user_id_input
            st.switch_page("pages/1_Scoring.py")
        else:
            st.error("User not found")

# ---------------------------
# REGISTER
# ---------------------------
if st.session_state.page == "register":
    st.subheader("Register")

    profession = st.text_input("Profession")
    country = st.text_input("Country")

    if st.button("Create User"):

        # ✅ Validation
        if profession.strip() == "" or country.strip() == "":
            st.warning("Please fill all fields")
            st.stop()

        user_id = str(uuid.uuid4())[:8]

        try:
            supabase.table("users").insert({
                "user_id": user_id,
                "profession": profession,
                "country": country,
                "created_at": datetime.now().isoformat()
            }).execute()

            st.success(f"✅ Your User ID: {user_id}")
            st.warning("⚠️ Save this ID for future login")

            st.session_state.user_id = user_id
            st.switch_page("pages/1_Scoring.py")

        except Exception as e:
            st.error("❌ Failed to create user")
