import streamlit as st
import pandas as pd
import uuid
from datetime import datetime
from supabase import create_client

st.set_page_config(page_title="BRISCO", layout="centered")

# -------supabase---------- 
url = st.secrets["SUPABASE_URL"] 
key = st.secrets["SUPABASE_KEY"] 
supabase = create_client(url, key)

# ---------------------------
# LOAD USERS (SAFE)
# ---------------------------
try:
    response = supabase.table("users").select("*").execute()
    users_data = response.data if response.data else []
    users_df = pd.DataFrame(users_data)
except Exception as e:
    st.error("❌ Could not load users")
    users_df = pd.DataFrame(columns=["user_id", "profession", "country"])

# ---------------------------
# UI: WELCOME PAGE
# ---------------------------
st.title("Welcome to BRISCO") 

st.markdown("""



BRISCO stands for **B**reast M**RI** **S**egmentation S**CO**ring. 
It is a plug-and-play web application designed for radiologists and researchers working in the field to evaluate the quality of breast MRI lesion segmentations, whether manual or generated by AI.

    """)
st.markdown("""
### Register/ Login as an Existing User

----


    """)
# ---------------------------
# NAVIGATION STATE
# ---------------------------
if "page" not in st.session_state:
    st.session_state.page = "home"

# ---------------------------
# HOME PAGE
# ---------------------------
if st.session_state.page == "home":

    col_left, col_center, col_right = st.columns([1, 2, 1])

    with col_center:
        btn_col1, btn_col2 = st.columns(2)

        with btn_col1:
            if st.button("Existing User"):
                st.session_state.page = "login"

        with btn_col2:
            if st.button("New User"):
                st.session_state.page = "register"

# ---------------------------
# LOGIN PAGE
# ---------------------------
elif st.session_state.page == "login":

    col_left, col_center, col_right = st.columns([1, 2, 1])

    with col_center:
        st.subheader("Login")
        user_id_input = st.text_input("Enter User ID")

        login_clicked = st.button("Login")

        if login_clicked:
            if users_df.empty:
                st.error("No users registered yet")
            elif user_id_input in users_df["user_id"].astype(str).values:
                st.session_state.user_id = user_id_input
                st.switch_page("pages/1_Scoring.py")
            else:
                st.error("User not found")

        # ✅ Always visible fallback
        st.markdown("---")
        if st.button("New user? Register here"):
            st.session_state.page = "register"
# ---------------------------
# REGISTER PAGE
# ---------------------------
elif st.session_state.page == "register":

    col_left, col_center, col_right = st.columns([1, 2, 1])

    with col_center:
        st.subheader("Register")

# ---------------------------
# DROPDOWN OPTIONS
# ---------------------------

        country_list = [
            "Afghanistan","Albania","Algeria","Andorra","Angola","Antigua and Barbuda","Argentina","Armenia","Australia",
            "Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin",
            "Bhutan","Bolivia","Bosnia and Herzegovina","Botswana","Brazil","Brunei","Bulgaria","Burkina Faso","Burundi",
            "Cabo Verde","Cambodia","Cameroon","Canada","Central African Republic","Chad","Chile","China","Colombia",
            "Comoros","Congo (Congo-Brazzaville)","Costa Rica","Croatia","Cuba","Cyprus","Czechia (Czech Republic)","Democratic Republic of the Congo",
            "Denmark","Djibouti","Dominica","Dominican Republic","Ecuador","Egypt","El Salvador","Equatorial Guinea","Eritrea","Estonia",
            "Eswatini (fmr. Swaziland)","Ethiopia","Fiji","Finland","France","Gabon","Gambia","Georgia","Germany","Ghana",
            "Greece","Grenada","Guatemala","Guinea","Guinea-Bissau","Guyana","Haiti","Holy See","Honduras","Hungary",
            "Iceland","India","Indonesia","Iran","Iraq","Ireland","Israel","Italy","Jamaica","Japan",
            "Jordan","Kazakhstan","Kenya","Kiribati","Kuwait","Kyrgyzstan","Laos","Latvia","Lebanon","Lesotho",
            "Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Madagascar","Malawi","Malaysia","Maldives","Mali",
            "Malta","Marshall Islands","Mauritania","Mauritius","Mexico","Micronesia","Moldova","Monaco","Mongolia","Montenegro",
            "Morocco","Mozambique","Myanmar (Burma)","Namibia","Nauru","Nepal","Netherlands","New Zealand","Nicaragua","Niger",
            "Nigeria","North Korea","North Macedonia","Norway","Oman","Pakistan","Palau","Palestine State","Panama","Papua New Guinea",
            "Paraguay","Peru","Philippines","Poland","Portugal","Qatar","Romania","Russia","Rwanda","Saint Kitts and Nevis",
            "Saint Lucia","Saint Vincent and the Grenadines","Samoa","San Marino","Sao Tome and Principe","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone",
            "Singapore","Slovakia","Slovenia","Solomon Islands","Somalia","South Africa","South Korea","South Sudan","Spain","Sri Lanka",
            "Sudan","Suriname","Sweden","Switzerland","Syria","Tajikistan","Tanzania","Thailand","Timor-Leste","Togo",
            "Tonga","Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Tuvalu","Uganda","Ukraine","United Arab Emirates","United Kingdom",
            "United States","Uruguay","Uzbekistan","Vanuatu","Venezuela","Vietnam","Yemen","Zambia","Zimbabwe"
        ]
        
        profession_list = [
            "Radiologist",
            "Academic Professor",
            "Researcher",
            "PostDoc",
            "PhD Student"
        ]
        
        # ---------------------------
        # INPUT FIELDS
        # ---------------------------
        
        profession = st.selectbox("Profession", profession_list)
        country = st.selectbox("Country", country_list)

        if st.button("Create User"):
            if profession.strip() == "" or country.strip() == "":
                st.warning("Please fill all fields")
                st.stop()

            user_id = str(uuid.uuid4())[:8]

            try:
                supabase.table("users").insert({
                    "user_id": user_id,
                    "profession": profession,
                    "country": country,
                    "created_at": datetime.now().isoformat()
                }).execute()

                st.success(f"✅ Your User ID: {user_id}")
                st.warning("⚠️ Save this ID for future login")

                st.session_state.user_id = user_id
                st.switch_page("pages/1_Scoring.py")

            except Exception as e:
                st.error("❌ Failed to create user")

st.markdown("""

----


    """)

st.markdown("""
### Terms of Use 

**How to use?** BRISCO web. app. expects an input of a MRI scan and its corresponding mask (manual or generated by AI) in same dimensions, in NIFTII format.
Only NIFTII files upto 200 MB are elligible for input. A viewer is available to see the overlap of the input mask and 
All information related to a user can be deleted by the user themselves by clicking the button. 
User IDs are randomnly generated hence users must remember their user ID to enter as an existing user and access their previous records. 
The user IDs are case sensitive. Hence please note them down. 
        
**Data privacy:** 
Only the entries 'Profession', 'Country' as part of the new registration are stored at the backend in Supabase to show the dashboard analytics and depict the use of the web. app. over time. 
NIFTI data input in the scoring form is not collected at the backend. The form entries are being stored in Supabase so that users can login again and also have access to their previous login entries. 
        
Tech stacks used: Supabase ( ), 
        
**Contacts:** This work has been developed by the researchers working at the Research Centre for Medical Image Analysis and AI, Department of Medicine, Danube Private University (DPU), Krems-3500, Austria. 
For queries or bugs related to the interface, email: Palak.Handa@dp-uni.ac.at. For queries related to the scoring form, email: Ramona.Woitek@dp-uni.ac.at
        
**Licence:** CC BY-NC. Commercial use is prohibited. Research collaborations and suggestions are welcome for further improvements. Credit must be given to the creaters. Hence, users must cite the following when using the code, data, web app, or any information generated through the web. app. 
{bibtex of the github}
{bibtex of the manuscript preprint}
        
**Limitations:** The web. app. is hosted through streamlit free version hence it may occasionally sleep and function slow. 
        """)
